/* global document, Blob, URL */
const state={records:[],files:new Map(),selected:null,original:new Map()};
const fields=['groupId','imageType','expectedBrandFamily','expectedProductName','expectedVariant','expectedMakerName','expectedAlcoholType','expectedVolumeMl','expectedAbv','expectedJanCode','difficulty','groundTruthStatus','notes'];
const list=document.querySelector('#list');const editor=document.querySelector('#editor');
document.querySelector('#truth').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;state.records=JSON.parse(await file.text());state.original=new Map(state.records.map(item=>[item.driveFileId,JSON.stringify(item)]));renderList()});
document.querySelector('#images').addEventListener('change',e=>{for(const file of e.target.files)state.files.set(file.name,file);renderList()});
document.querySelector('#search').addEventListener('input',renderList);
document.querySelector('#export').addEventListener('click',()=>{const changed=state.records.filter(item=>state.original.get(item.driveFileId)!==JSON.stringify(item));const blob=new Blob([JSON.stringify({reviewedAt:new Date().toISOString(),records:changed},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ground-truth-review-diff.json';a.click();URL.revokeObjectURL(a.href)});
function renderList(){const query=document.querySelector('#search').value.toLowerCase();list.replaceChildren(...state.records.filter(item=>`${item.fileName} ${item.expectedProductName??''}`.toLowerCase().includes(query)).map(item=>{const button=document.createElement('button');button.className=`row ${state.selected===item.driveFileId?'active':''}`;button.textContent=`${item.fileName} · ${item.groundTruthStatus}`;button.onclick=()=>{state.selected=item.driveFileId;renderList();renderEditor(item)};return button}))}
function renderEditor(item){const file=state.files.get(item.fileName);const preview=file&&/jpe?g|png|webp/i.test(file.type||file.name)?`<img class="preview" src="${URL.createObjectURL(file)}">`:'<p>HEICはブラウザの対応状況によりプレビューできません。ファイル名と既存解析結果で確認してください。</p>';editor.innerHTML=`<h2>${item.fileName}</h2>${preview}<div class="grid">${fields.map(field=>`<label class="${field==='notes'?'wide':''}">${field}<input data-field="${field}" value="${String(item[field]??'').replaceAll('"','&quot;')}"></label>`).join('')}</div>`;for(const input of editor.querySelectorAll('[data-field]'))input.onchange=()=>{const value=input.value.trim();item[input.dataset.field]=/^(expectedVolumeMl|expectedAbv)$/.test(input.dataset.field)&&value?Number(value):value||undefined}}
